general {
    lock_cmd = "pidof swaylock || swaylock"
    unlock_cmd = "pkill swaylock"
    before_sleep_cmd = "loginctl lock-session"
    after_sleep_cmd = "loginctl unlock-session"
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = "swaymsg 'output * dpms off'"
    on-resume = "swaymsg 'output * dpms on'"
}

listener {
    timeout = 600
    on-timeout = "systemctl suspend"
}
